"""Backend services for the FireTwin Explorer forecast catalog."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, cast

DEFAULT_REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_MANIFEST_PATH = DEFAULT_REPO_ROOT / "data/manifests/firms_next_day_explorer_manifest.json"


class ExplorerCatalogError(RuntimeError):
    """Raised when the Explorer forecast catalog cannot be loaded or queried."""


def load_explorer_manifest(manifest_path: Path = DEFAULT_MANIFEST_PATH) -> dict[str, Any]:
    """Load and validate the committed Explorer manifest."""
    if not manifest_path.is_file():
        raise ExplorerCatalogError(f"Explorer manifest not found: {manifest_path}")

    raw_manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if not isinstance(raw_manifest, dict):
        raise ExplorerCatalogError("Explorer manifest must be a JSON object")
    manifest = cast(dict[str, Any], raw_manifest)
    cases = manifest.get("cases")
    if not isinstance(cases, list) or not cases:
        raise ExplorerCatalogError("Explorer manifest must contain at least one case")
    if manifest.get("not_operational") is not True:
        raise ExplorerCatalogError("Explorer manifest must retain not_operational=true")
    return manifest


def list_explorer_cases(manifest: dict[str, Any]) -> list[dict[str, Any]]:
    """Return public case summaries for API clients."""
    return [
        {
            "case_id": case["case_id"],
            "case_name": case["case_name"],
            "reference_time": case["reference_time"],
            "target_time": case["target_time"],
            "peak_probability": case["sample_peak_probability"],
            "observed_brier_score": case["observed_brier_score"],
            "persistence_brier_score": case["persistence_brier_score"],
            "brier_improvement_vs_persistence": case["brier_improvement_vs_persistence"],
            "preview_png": case["preview_png"],
        }
        for case in manifest["cases"]
    ]


def get_explorer_case(manifest: dict[str, Any], case_id: str) -> dict[str, Any]:
    """Return one Explorer case from the manifest."""
    for case in manifest["cases"]:
        if case["case_id"] == case_id:
            return cast(dict[str, Any], case)
    raise ExplorerCatalogError(f"Unknown Explorer case: {case_id}")


def build_forecast_response(
    manifest: dict[str, Any],
    *,
    case_id: str,
) -> dict[str, Any]:
    """Build the first API forecast response for a selected fire case.

    The current backend response is artifact-backed: it serves the validated leave-one-fire-out
    forecast product generated by FireTwin. Keeping this as an API boundary lets the public
    Explorer use the same contract that later on-demand inference will implement.
    """
    case = get_explorer_case(manifest, case_id)
    return {
        "case_id": case["case_id"],
        "case_name": case["case_name"],
        "forecast_mode": "artifact_backed_live_api",
        "model_family": "observed_label_logistic_sgd",
        "forecast_semantics": case["forecast_semantics"],
        "target_type": case["target_type"],
        "not_operational": manifest["not_operational"],
        "reference_time": case["reference_time"],
        "target_time": case["target_time"],
        "recommended_threshold": case["recommended_threshold"],
        "sample_index": case["sample_index"],
        "preview_png": case["preview_png"],
        "metrics": {
            "observed_brier_score": case["observed_brier_score"],
            "persistence_brier_score": case["persistence_brier_score"],
            "brier_improvement_vs_persistence": case["brier_improvement_vs_persistence"],
            "expected_calibration_error": case["expected_calibration_error"],
            "precision": case["recommended_precision"],
            "recall": case["recommended_recall"],
            "f1_score": case["recommended_f1_score"],
        },
        "footprint": {
            "peak_probability": case["sample_peak_probability"],
            "mean_probability": case["sample_mean_probability"],
            "predicted_positive_fraction": case["sample_predicted_positive_fraction"],
            "target_positive_fraction": case["sample_target_positive_fraction"],
        },
        "provenance": {
            "forecast_artifact": case["forecast_artifact"],
            "selection_rule": case["selection_rule"],
            "grid_shape": case["grid_shape"],
            "grid_crs": case["grid_crs"],
            "resolution_m": case["resolution_m"],
        },
        "guardrails": manifest["guardrails"],
    }
