"""Fire spread forecast models and baselines."""

from firetwin.models.baselines import EllipticalBaseline, PersistenceBaseline, RadialBaseline
from firetwin.models.firms_next_day import (
    FIRMSForecastArtifactSummary,
    FIRMSLearnedModelResult,
    ObservedLabelLogisticModel,
    build_firms_next_day_forecast_dataset,
    build_leave_one_fire_out_forecast_artifacts,
    evaluate_learned_model_leave_one_fire_out,
    predict_observed_label_probability,
    render_forecast_artifact_report,
    render_learned_model_report,
    train_observed_label_logistic_model,
)
from firetwin.models.hybrid import (
    HYBRID_MODEL_NAME,
    HybridBlendEvaluation,
    HybridBlendModel,
    evaluate_hybrid_blend,
    fit_hybrid_blend_model,
    hybrid_blend_probability,
    render_hybrid_blend_report,
)
from firetwin.models.surrogate import (
    SIMULATION_SURROGATE_MODEL_NAME,
    SimulationLatencyBenchmarkRow,
    SimulationLatencyBenchmarkSummary,
    SimulationScenarioControls,
    SimulationSurrogateEvaluation,
    SimulationSurrogateModel,
    SimulationSurrogateTrainingSummary,
    benchmark_simulation_surrogate_latency,
    evaluate_simulation_surrogate_leave_one_out,
    fire_case_from_simulation_sample,
    fit_and_save_simulation_surrogate,
    load_simulation_corpus_manifest,
    load_simulation_surrogate_model,
    predict_simulation_sample,
    predict_simulation_sample_with_controls,
    render_simulation_latency_report,
    render_simulation_surrogate_report,
    save_simulation_surrogate_model,
    train_simulation_surrogate,
)

__all__ = [
    "PersistenceBaseline",
    "RadialBaseline",
    "EllipticalBaseline",
    "FIRMSLearnedModelResult",
    "FIRMSForecastArtifactSummary",
    "ObservedLabelLogisticModel",
    "train_observed_label_logistic_model",
    "predict_observed_label_probability",
    "evaluate_learned_model_leave_one_fire_out",
    "render_learned_model_report",
    "build_firms_next_day_forecast_dataset",
    "build_leave_one_fire_out_forecast_artifacts",
    "render_forecast_artifact_report",
    "HYBRID_MODEL_NAME",
    "HybridBlendModel",
    "HybridBlendEvaluation",
    "hybrid_blend_probability",
    "fit_hybrid_blend_model",
    "evaluate_hybrid_blend",
    "render_hybrid_blend_report",
    "SIMULATION_SURROGATE_MODEL_NAME",
    "SimulationLatencyBenchmarkRow",
    "SimulationLatencyBenchmarkSummary",
    "SimulationScenarioControls",
    "SimulationSurrogateEvaluation",
    "SimulationSurrogateModel",
    "SimulationSurrogateTrainingSummary",
    "benchmark_simulation_surrogate_latency",
    "train_simulation_surrogate",
    "predict_simulation_sample",
    "predict_simulation_sample_with_controls",
    "fire_case_from_simulation_sample",
    "evaluate_simulation_surrogate_leave_one_out",
    "fit_and_save_simulation_surrogate",
    "load_simulation_corpus_manifest",
    "save_simulation_surrogate_model",
    "load_simulation_surrogate_model",
    "render_simulation_latency_report",
    "render_simulation_surrogate_report",
]
